== Built-Ins

Built-Ins are interpolation operations which are called on the current value of the interpolation.

.Example with `upper_case` built-in
[source,java]
----
private final Configuration configuration = new Configuration();
private Template template = configuration.getTemplate("test", "HELLO ${example?upper_case}!");
System.out.println(template.process(Map.of("example", "world")));
----

In the above example the built-in `upper_case` is called on the current value `world` of the interpolation.
The built-in converts a text to its uppercase form.

Since the capitalization can only be changed for text, the execution of this built-in on other types such as numbers or dates is forbidden. In general, all built-ins are assigned to a type and an exception is thrown if a wrong type is used.

if a built-in seems to apply to multiple types, it's because each type has a built-in with the same name.

It is possible to use more than one built-in in an interpolation.
The built-ins are called from left to right on the current value of the interpolation.
This means a built-inn is called on the result of a previous built-in or the initial value.

.Example with two built-ins
[source,java]
----
private final Configuration configuration = new Configuration();
private Template template = configuration.getTemplate("test", "HELLO ${example?upper_case?lowercase}!");
System.out.println(template.process(Map.of("example", "WorlD")));
----

In the example above the `upper_case` built-in is called on the current value `WorlD`.
The second built-in `lower_case` is called on the current value `WORLD`, which is the result of `upper_case`.
the result of the interpolation is the result `world` of the second built-in.

=== String Built-Ins

==== `uppercase` Built-In

This Built-In converts a text in its uppercase form.

|===
|Input | Output

|The quick brown Fox jumps over the lazy Dog
|THE QUICK BROWN FOX JUMPS OVER THE LAYZ DOG
|===

==== `lowercase` Built-In

This Built-In converts a text in its lowercase form.

|===
|Input | Output

|The quick brown Fox jumps over the lazy Dog
|the quick brown fox jumps over the lazy dog
|===

==== `capitalize` Built-In

This Built-In converts the first letter of each word to uppercase.
A word with a first lowercase letter means `\b(\p{javaLowerCase})(\p{IsAlphabetic}*)\b`

|===
|Input | Output

|The quick brown Fox jumps over the lazy Dog
|The Quick Brown Fox Jumps Over The Lazy Dog
|===

==== `camelCase` Built-In

This Built-In converts a text from _snake_case_, _screaming_snake_case_ or _kebab-case_ to _camelCase_.
The result may look strange is the input is in some other format.

|===
|Input | Output

m|The-quick-brown-Fox-jumps-over-the-lazy-Dog
m|theQuickBrownFoxJumpsOverTheLazyDog

m|The_quick_brown_Fox_jumps_over_the_lazy_Dog
m|theQuickBrownFoxJumpsOverTheLazyDog
|===

==== `snake_case` Built-In

This Built-In converts a text from _camelCase_ to _snake_case_.
The result may look strange is the input is in some other format.

|===
|Input | Output

m|theQuickBrownFoxJumpsOverTheLazyDog
m|The_quick_brown_Fox_jumps_over_the_lazy_Dog
|===

==== `screaming_snake_case` Built-In

This Built-In converts a text from _camelCase_ to _screaming_snake_case_.
The result may look strange is the input is in some other format.

|===
|Input | Output

m|theQuickBrownFoxJumpsOverTheLazyDog
m|THE_QUICK_BROWN_FOX_JUMPS_OVER_THE_LAZY_DOG
|===

==== `kebab_case` Built-In

This Built-In converts a text from _camelCase_ to _kebab-case_.
The result may look strange is the input is in some other format.

|===
|Input | Output

m|theQuickBrownFoxJumpsOverTheLazyDog
m|The-quick-brown-Fox-jumps-over-the-lazy-Dog
|===

==== `trim` Built-In

This Built-In removes leading and trailing whitespaces from the text.
The examples uses `␣` as an replacement for the whitespace.

|===
|Input | Output

m|␣␣␣The␣quick␣brown␣Fox␣jumps␣over␣the␣lazy␣Dog␣␣
m|The␣quick␣brown␣Fox␣jumps␣over␣the␣lazy␣Dog
|===

==== `contains` Built-In

This Built-In return `true` if the text contains the specified parameter, otherwise `false`.

|===
|Interpolation | Output

m|${'The quick brown Fox jumps over the lazy Dog'?contains('Fox')}
m|true

m|${'The quick brown Fox jumps over the lazy Dog'?contains('Cat')}
m|false
|===

==== `endsWith` Built-In

This Built-In return `true` if the text ends with the specified parameter, otherwise `false`.

|===
|Interpolation | Output

m|${'The quick brown Fox jumps over the lazy Dog'?endsWith('Fox')}
m|true

m|${'The quick brown Fox jumps over the lazy Dog'?ends_with('Cat')}
m|false
|===

==== `toBoolean` Built-In

This Built-In return `true` if the text is `true` and `false` if it is `false`.

|===
|Interpolation | Output

m|${'true'?toBoolean}
m|true

m|${'false'?to_boolean}
m|false

m|${'gonzo'?toBoolean}
| This is an error.
|===

==== `length` Built-In

This Built-In return the length of the text.

|===
|Interpolation | Output

m|${'true'?length}
m|4

m|${'false'?length}
m|5
|===

==== `esc` Built-In

TBD

==== `noEsc` Built-In

TBD

=== Boolean Built-Ins

==== `c` (computer language) Built-In

This Built-In converts a boolean to the string literals `true` or `false`.

==== `then` Built-In

This Built-In returns its first parameter the value is `true` or the second parameter if the value is  `false`.

|===
|Interpolation | Output

m|${true?then(23, 42)}
m|23

m|${false?then(23, 42)}
m|42
|===

==== `string` Built-In

This Built-In returns its first string parameter the value is `true` or the second string parameter if the value is  `false`.
The `string` Built-In is replaceable by the `then` Built-In.
|===
|Interpolation | Output

m|${true?string('Fox', 'Dog')}
m|Fox

m|${false?string('Fox', 'Dog')}
m|Dog
|===

=== Date-Time Built-Ins

==== `date` Built-In

This Built-In returns the date part of the value.

==== `time` Built-In

This Built-In returns the time part of the value.

==== `c` (computer language) Built-In

This Built-In returns a timestamp string of the value.

=== Date Built-Ins

==== `date` Built-In

This Built-In returns the date part of the value.

==== `c` (computer language) Built-In

This Built-In returns a timestamp string of the value.

=== Time Built-Ins

==== `time` Built-In

This Built-In returns the time part of the value.

==== `c` (computer language) Built-In

This Built-In returns a timestamp string of the value.

=== Enum Built-Ins

==== `ordinal` Built-In

This Built-In returns the ordinal of the value.

==== `c` (computer language) Built-In

This Built-In returns the name of the value.

=== File and Path Built-Ins

==== `exists` Built-In

This Built-In returns true, if the file/path in the value exists.

==== `is_directory` Built-In

This Built-In returns true, if the file/path in the value is a directory.

==== `is_file` Built-In

This Built-In returns true, if the file/path in the value is a file.

==== `can_execute` Built-In

This Built-In returns true, if the file/path in the value can be executed.

==== `can_read` Built-In

This Built-In returns true, if the file/path in the value can be read.

==== `can_write` Built-In

This Built-In returns true, if the file/path in the value can be write.

==== `size` Built-In

This Built-In returns the size of the file/path in the value.

==== `name` Built-In

This Built-In returns the name of the file/path in the value.

==== `parent` Built-In

This Built-In returns the parent file/path of the value.

=== Looper Built-Ins

==== `index` Built-In

This Built-In returns the index (starting with zero) of the current loop value.

==== `counter` Built-In

This Built-In returns the counter (starting with one) of the current loop value.

==== `is_first` Built-In

This Built-In returns `true`, if the current loop value is the first one and `false` otherwise.

==== `is_last` Built-In

This Built-In returns `true`, if the current loop value is the last one and `false` otherwise.

==== `item_parity` Built-In

This Built-In returns `even`, if the current loop counter is even and `odd` otherwise.

==== `item_parity_cap` Built-In

This Built-In returns `Even`, if the current loop counter is even and `Odd` otherwise.

==== `item_cycle` Built-In

TBD

==== `has_next` Built-In

This Built-In returns `false`, if the current loop value is the last one and `true` otherwise.
