=== Looper Built-Ins

==== `index` Built-In

This built-in returns the index (starting with zero) of the current loop value as a number value.

|===
|Template |Output

a|
----
<#list (1..10) as s, l>${l?index}, </#list>
----
m|0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
|===

==== `counter` Built-In

This built-in returns the counter (starting with one) of the current loop value as a number value.

|===
|Template |Output

a|
----
<#list (1..10) as s, l>${l?counter}, </#list>
----
m|1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
|===

==== `is_first` Built-In

This built-in returns the boolean value `true`, if the current loop value is the first one and `false` otherwise.

|===
|Template |Output

a|
----
<#list (1..10) as s, l>${l?is_first}, </#list>
----
m|true, false, false, false, false, false, false, false, false, false,
|===

==== `is_last` Built-In

This built-in returns the boolean value `true`, if the current loop value is the last one and `false` otherwise.

|===
|Template |Output

a|
----
<#list (1..10) as s, l>${l?is_last}, </#list>
----
m|false, false, false, false, false, false, false, false, false, true,
|===

==== `item_parity` Built-In

This built-in returns the string value `even`, if the current loop counter is even and `odd` otherwise.


|===
|Template |Output

a|
----
<#list (1..10) as s, l>${l?is_last}, </#list>
----
m|false, false, false, false, false, false, false, false, false, true,
|===

==== `item_parity_cap` Built-In

This built-in returns the string value `Even`, if the current loop counter is even and `Odd` otherwise.

==== `item_cycle` Built-In

TBD

==== `has_next` Built-In

This built-in returns `false`, if the current loop value is the last one and `true` otherwise.

