== Customization

=== Customization by `Configuration`

TBD

=== Customization by `TemplateBuilder`

TBD

==== With Clock

TBD

.Example builder with fixed clock
[source,java]
----
Configuration config = new Configuration();
Instant instant = ZonedDateTime.of(1968, 8, 24, 12, 30, 0, 0,ZoneOffset.UTC).toInstant();
TemplateBuilder builder = config.builder().withClock(Clock.fixed(instant, ZoneOffset.UTC));
----

==== With Locale

TBD

.Example builder with german locale
[source,java]
----
Configuration config = new Configuration();
TemplateBuilder builder = config.builder().withLocale(Locale.GERMANY);
----

==== With Zone-ID

TBD

.Example builder with "Europe/Berlin" Zone-ID
[source,java]
----
Configuration config = new Configuration();
TemplateBuilder builder = config.builder().withZoneId(ZoneId.of("Europe/Berlin"));
----

=== With Output-Format

TBD

.Example builder with AsciiDoctor Output-Format
[source,java]
----
Configuration config = new Configuration();
TemplateBuilder builder = config.builder().withOutputFormat(StandardOutputFormats.ADOC);
----


==== Custom Formatter

The default formatting for number and temporal values can be changed with the
`Configuration#registerFormatter(String, String)` method.

The first parameter `type` specifies the value type `number`, `zoned-date-time` (for `Instant` and `ZonedDateTime`), `date-time` (for `LocalDateTime`), `date` (for `LocalDate`) and `time` (for `LocalTime`). The second parameter is a pattern of `DecimalFormatter` or `DateTimeFormatter`.

.Example with custom number and temporal formatting
[source,java]
----
Configuration config = new Configuration();
config.registerFormatter("number", "#.00");
TemplateBuilder templateBuilderWithNumber = config.builder();
config.registerFormatter("date", "dd. MM. yyyy");
config.registerFormatter("time", "HH:mm");
TemplateBuilder templateBuilderWithNumberAndTemporal = config.builder();
----

TBD

=== Custom String Types

Unknown _Java_ classes are usually treated like beans. However, this is not desired in many cases. If the _ToString_ representation of an object is to be used in the output, its class can be registered via `registerSimpleMapping(Class<?> type)` for this purpose.

Alternatively, the method `registerSimpleMapping(Function<Object, String> mapping)` can be used if further adjustments are to be made.

.Example with Leitweg-ID and `toString` method
[source,java,role="primary"]
----
Configuration config = new Configuration();
config.registerSimpleMapping(LeitwegId.class);
TemplateBuilder templateBuilder = config.builder();
Template template = templateBuilder.getTemplate("id", "ID: ${id}!");
LeitwegId leitwegId = LeitwegId.parse("04011000-1234512345-06");
String resullt = template.process(Map.of("id", leitwegId));
// ID: 04011000-1234512345-06!
----

.Example with Leitweg-ID and converting `Function`
[source,java,role="secondary"]
----
Configuration config = new Configuration();
configuration.registerSimpleMapping(LeitwegId.class, lid -> "<<" + lid + ">>");
TemplateBuilder templateBuilder = config.builder();
Template template = templateBuilder.getTemplate("id", "${id}!");
LeitwegId leitwegId = LeitwegId.parse("04011000-1234512345-06");
String resullt = template.process(Map.of("id", leitwegId));
// ID: <<04011000-1234512345-06>>!
----

=== Custom `OutputFormat`

TBD

[source,java]
----
include::../java/org/freshmarker/core/output/OutputFormat.java[lines="6..-1"]
----

=== Custom primitive Model Types

==== Evaluate Value

TBD

==== Type Mapper

TBD

==== Operator Overloading

TBD

=== Custom Plug-Ins

The _Plug-in_ mechanism is the core of _FreshMarker_'s modular extension concept. _Plug-ins_ can be used to add new types, formatters, functions, user directives, built-ins and mappers.

It is possible to create completely new template types or to add further features to existing ones.

In addition to the existing plug-ins for the _FreshMarker_ basic types, you can also develop your own _Plug-ins_.

Plug-ins can be registered with _FreshMarker_ via the `ServiceLoader` mechanism or via the `Configuration#registerPlugin` method.

[source,java]
----
include::../java/org/freshmarker/core/plugin/PluginProvider.java[lines="16..-1"]
----

TBD