== Customization

=== `Configuration`

==== Custom Formatter

The default formatting for number and temporal values can be changed with the
`Configuration#registerFormatter(String, String)` method.

The first parameter `type` specifies the value type `number`, `zoned-date-time` (for `Instant` and `ZonedDateTime`), `date-time` (for `LocalDateTime`), `date` (for `LocalDate`) and `time` (for `LocalTime`). The second parameter is a pattern of `DecimalFormatter` or `DateTimeFormatter`.

.Example with custom number and temporal formatting
[source,java]
----
Configuration configuration = new Configuration();
configuration.registerFormatter("number", "#.00");
TemplateBuilder templateBuilderWithNumber = configuration.builder();
configuration.registerFormatter("date", "dd. MM. yyyy");
configuration.registerFormatter("time", "HH:mm");
TemplateBuilder templateBuilderWithNumberAndTemporal = configuration.builder();
----

TBD

=== `TemplateBuilder`

TBD

=== Custom String Types

Unknown _Java_ classes are usually treated like beans. However, this is not desired in many cases. If the _ToString_ representation of an object is to be used in the output, its class can be registered for this purpose.

.Example with Leitweg-ID as String
[source,java]
----
Configuration configuration = new Configuration();
configuration.registerSimpleMapping(LeitwegId.class);
TemplateBuilder templateBuilder = configuration.builder();
Template template = templateBuilder.getTemplate("id", "ID: ${id}!");
LeitwegId leitwegId = LeitwegId.parse("04011000-1234512345-06");
String resullt = template.process(Map.of("id", leitwegId));
// ID: 04011000-1234512345-06!
----

.Example with Leitweg-ID as String
[source,java]
----
Configuration configuration = new Configuration();
configuration.registerSimpleMapping(LeitwegId.class, lid -> "<<" + lid + ">>");
TemplateBuilder templateBuilder = configuration.builder();
Template template = templateBuilder.getTemplate("id", "${id}!");
LeitwegId leitwegId = LeitwegId.parse("04011000-1234512345-06");
String resullt = template.process(Map.of("id", leitwegId);
// ID: <<04011000-1234512345-06>>!
----

=== Custom `OutputFormat`

TBD

[source,java]
----
public interface OutputFormat {
    default TemplateString escape(Environment environment, String value) {
        return new TemplateString(value);
    }

    default TemplateString comment(Environment environment, String value) {
        return TemplateString.EMPTY;
    }
}
----

=== Custom primitive Model Types

==== Evaluate Value
TBD

==== Type Mapper

TBD

==== Operator Overloading

TBD

=== Custom Plug-Ins

The _Plug-in_ mechanism is the core of _FreshMarker_'s modular extension concept. _Plug-ins_ can be used to add new types, formatters, functions, user directives, built-ins and mappers.

It is possible to create completely new template types or to add further features to existing ones.

In addition to the existing plug-ins for the _FreshMarker_ basic types, you can also develop your own _Plug-ins_.

Plug-ins can be registered with _FreshMarker_ via the `ServiceLoader` mechanism or via the `Configuration#registerPlugin` method.

[source,java]
----
public interface PluginProvider {
  default void registerMapper(Map<Class<?>, Function<Object, TemplateObject>> mapper) {}

  default void registerFormatter(Map<Class<? extends TemplateObject>, Formatter> formatter) {}

  default void registerBuildIn(Map<BuiltInKey, BuiltIn> builtIns) {}

  default void registerTemplateObjectProvider(List<TemplateObjectProvider> providers) {}

  default void registerUserDirective(Map<String, UserDirective> directives) {}

  default void registerFunction(Map<String, TemplateFunction> functions) {}
}
----

TBD