== Directives

=== If/ElseIf/Else Directive

This directive generates conditional output. The expression in the `if` and `elseif` statement
is evaluated to a boolean value. If the value is `true` the corresponding block is evaluated.
If the expression cannot evaluate to a boolean value an exception is thrown.

.Example with only the `if` part
[source]
----
<#if text??>
${text}
</#if>
----

The `elseif` and `else` part are optional and can be dismissed.

.Example with all parts
[source]
----
<#if number >= 100>
greater equal hundred
<#elseif number > 10>
greater ten
<#else>
less ten
</#if>
----

=== Switch/Case/Default Directive

This directive generates conditional output.
But unlike the _If Directive_, only one expression int the `switch` statement is evaluated.
Each `case` statement handles a possible outcome of the evaluation.
If none of the specified `case` statements match, then the `default` statement is used.

NOTE: the FreshMarker _Switch Directive_ does not support fall-through, so `break` statements are unnecessary.

[source]
----
<#switch color>
<#case 'RED'>#FF0000
<#case 'GREEN'>#00FF00
<#case 'BLUE'>#0000FF
<#default>${color}
</#switch>
----

=== List Directive

The _List Directives_ processes its body for each element of a sequence. The sequence can be either a list, a hash or a range.
A list directive exists in two variants.
The first variant defines the sequence and the name of the item variable in the block.

The second variant defines the sequence, the name of the item variable in the block and a loop variable with metadata of the current loop iteration.

IMPORTANT: Although _FreeMarker_ and _FreshMaker_ are similar, the list directive syntax differs. _FreeMarker_ does not know a separate loop variable. The syntax here conflicts with the _FreeMarker_ syntax for hashes.

==== List Directive with a list

A list is a sequence of values of any model type.

.List Directive example with a list
[source]
----
<#list sequence as s>
${s} Marx
</#list>
----

In the above example, each element from the list is simply output followed by the word `Marx`.
If the list contains `Chico`, `Harpo`, `Groucho`, `Gummo` and `Zeppo` then the result is a five-line listing of the Marx brothers.

The next example the interpolation `${s}` is preceded by the interpolation `${l?counter}`.

.List Directive example with a list and a loop variable
[source]
----
<#list sequence as s, l>
${l?counter}. ${s} Marx
</#list>
----

Because `l` is the name of the loop variable, the first interpolation evaluates to the counter of the current item in the list.

[source]
----
1. Chico Marx
2. Harpo Marx
3. Groucho Marx
4. Gummo Marx
5. Zeppo Marx
----

==== List Directive with a range

A range is defined by a lower and a non-mandatory upper numerical limit.
Although `FreshMarker` also masters right-open ranges, List Directives are not allowed to use them.

.List Directive example with a range
[source]
----
<#list 1..5 as s>
${s} * ${s} = ${s*s}
</#list>
----

The current item in the above example is any integer value from 1 to 5 inclusive.
The result is a list of square value equations.

[source]
----
1 * 1 = 1
2 * 2 = 4
3 * 3 = 9
4 * 4 = 16
5 * 5 = 25
----

Because the limits of a range do not have to be constants, a List Directive can also be used to mimic a for loop.

.List Directive example with variable range limits
[source]
----
<#list a..b as s>
${s} * ${s} = ${s*s}
</#list>
----

This example loops through all values between numeric variable `a` and numeric variable `b`.
For the value `3` in `a` and `1` in `b` the following result is generated.

[source]
----
3 * 3 = 9
2 * 2 = 4
1 * 1 = 1
----

==== List Directive with a hash

A hash is a sequence of key-value pairs. The key is a string and the value is any model type.

For a hash the item is a key-value pair in parentheses.

.List Directive example with a hash
[source]
----
<#list map as (key, value)>
${key}->${value}
</#list>
----

.List Directive example with a hash and a loop variable
[source]
----
<#list map as (key, value), l>
${l?counter}. ${key}->${value}
</#list>
----

=== Var/Set Directive

[source]
----
<#var test='eins'/>
<#set test='zwei'/>
<#set test='drei'/>
----

=== Output-Format Directive

TBD

=== Setting Directive

[source]
----
<#setting locale="de_DE">
${42.23}
<#setting locale="en_US">
${42.23}
----

=== Macro Directive

TBD

=== User Directive

[source]
----
<@log level='info' message='test'/>
----

