== Model

The template engine needs data to fill the interpolations.
Because it is an embedded _Java_ engine, normal _Java_ classes are used.
A map is always used as the model for calling the engine.

By default, the template engine supports `String`, Number like `Integer`, `Long`, `Double` and `Float`, `Boolean` and Date Types as base types.
In addition, the engine also knows `List`, `Map`, Sequences, Records and Beans.

The top level model is a `Map<String, Object>`, which contains the top level values by their names.

.Example Model
[source,java]
----
Map<String, Object> model = Map.of("father", father, "mother", mother);
----

The following tables show all model types supported by _FreshMarker_.
Because _FreshMarker_ can be extended, there are more types available
footnote:[The library https://gitlab.com/schegge/telephone[Telephone] adds the `InternationalPhoneNumber` support.].

Without a package specification, the class names refer to the classes of the same name from the JDK.

.Supported Model Types
|===
|Type | _Java_ Type(s) | _FreshMarker_ primitive type

|String|`String`, `StringBuilder`, `StringBuffer`|yes
|String|`UUID`, `URI`, `URL`|yes
|Number|`BigInteger`, `Long`, `Integer`, `Short`, `Byte`|yes
|Number|`long`, `int`, `short`, `byte`, `double`, `float`|yes
|Number|`BigDecimal`, `Double`, `Float`|yes
|Number|`AtomicLong`, `AtomicInteger`|yes
|Boolean|`Boolean`, `boolean`|yes
|DateTime|`Instant`, `ZonedDateTime`, `LocalDateTime`, `Date`|yes
|Date|`LocalDate`, `java.sql.Date`|yes
|Time|`LocalTime`, `java.sql.Time`|yes
|Duration|`Duration`|yes
|File|`File`|yes
|Path|`Path`|yes
|Period|`Period`|yes
|Sequence|Lists|no
|Range|-|no
|Slice|-|no
|Map|Maps|no
|Bean|Beans|no
|Record|Top-Level Records|no
|Enum|Enums|yes
|Null|-|yes
|Locale|`Locale`|yes
|Version|-|yes
|===

All primitive types, except Null, have a default representation via their `toString` method.
This must be considered with the enums, because the `toString` method can be overridden.

=== Ranges and Slices

==== Ranges

Ranges are data structures that represent an interval with a lower limit and an optional upper limit.

Ranges without an upper limit are called _right-unlimited ranges_, ranges with an upper limit are called _right-limited ranges_.
If the size of the interval is specified instead of the upper limit, then this range is called a _length-limited range_.

===== Right-unlimited Range

In principle, a right-unlimited range has no upper limit and can therefore only be used in a few places.

The main area of application is slicing, where a part is cut out of a list, `String` or range.
3
A right unlimited range has the form `_x_..` where `_x_` can be any numerical expression.

.Example right-unlimited ranges
[source,subs="verbatim,quotes"]
----
1..   // lower bound 1
-10.. // lower bound -10
a..   // lower bound in the variable _a_ (must be a numeric value)
----

===== Right-limited Range

A _right-limited range_ has a lower and an upper limit. It also represents a sequence of numbers and can be used in this way in a list directive. A _right-limited range_ has the form `_x_.._y_` or  `_x_..+++<+++_y_` where `_x_` and `_y_` can be any numeric expression. The second form describes a range with an exclusive upper limit. This form is called a _right-limited exclusive range_.

.Example right-limited ranges
[source,subs="verbatim,quotes"]
----
1..10   // lower bound 1 and upper bound 10
-10..<0 // lower bound -10 and upper bound -1
a..b    // lower bound in variable _a_ and upper bound in variable _b_
10..0   // lower bound 1 and upper bound 10
a..<b   // lower bound in variable _a_ and an exclusive upper bound in variable _b_
----

As can be seen in the examples, the lower limit may be greater than the upper limit. This means that the representation as a sequence cannot be monotonically increasing, but can be monotonically decreasing. In the case of a monotonically increasing sequence, we speak of a _legal range_, otherwise of an _inverse range_.

===== Length-limited Range (since 1.6.4)

A _length-limited range_ is a _right-limited range_ with a different syntax `_a_..*_c_`. 
Where `a` again corresponds to the lower limit of the range and `c` indicates the size of the range.

If the size of the range is positive, then the upper limit is greater than the lower limit. This results in a _legal right-limited range_. If the size of the range is negative, then the upper limit is smaller than the lower limit. This results in an _inverted right-limited range_.

.Example length-limited ranges
[source,subs="verbatim,quotes"]
----
1..\*10  // lower bound 1 and upper bound 10
5..*5   // lower bound 5 and upper bound 9
4..*-5  // lower bound 4 and upper bound 0
a..*b   // lower bound in variable _a_ and an range size in variable _c_
----

==== Slices

TBD

=== Lazy Values

Normally the values are written directly into the model.
Sometimes the cost of creating optional values is quite high.
In that case it would be a waste to calculate the values if they are not used.
However, since _FreshMarker_ needs the values in the model, a compromise is made.
Instead of calculating the values immediately and placing them in the map, the calculation is inserted into the model as a `TemplateObjectSupplier`.
Their actual values are lazy evaluated only when accessed during processing.

.Example lazy values
[source,java]
----
Map<String, Object> model = Map.of(
  "familyTree", TemplateObjectSupplier.of(() -> fetchTreeFromDataBase(name)),
  "name", "Kayser");
template.process(model);
----

In the example above, the `familyTree` value is lazy evaluated, when the variable is accessed during template processing.

=== Forbidden Types

Although many Java types are supported directly or as a Java Bean, some classes cannot be used. For security reasons, all classes from the `java`, `javax`, `sun` and `com.sun` packages are ignored.

if you desperately need one of these classes, you can declare it as an exception.

.Example allowed system classes
[source,java]
----
configuration.getSecurity().addAllowedClass(Runtime.class);
configuration.getSecurity().addAllowedPackages(java.lang.annotation.Annotation.class);
configuration.getSecurity().addAllowedPackages("java.io");
----

NOTE: Of course, it only makes sense to allow classes that can also be interpreted by _FreshMarker_. Alternatively, a class can also be integrated via _Custom String Types_ or a _Plug-in_.

In the example above, the class `java.lang.Runtime` and all classes in the packages `java.lang.annotation` and `java.io` and all of their subpackages are allowed.