== Model

The template engine needs data to fill the interpolations.
Because it is an embedded Java engine, normal Java classes are used.
A map is always used as the model for calling the engine.

By default, the template engine supports `String`, Number like `Integer`, `Long`, `Double` and `Float`, `Boolean` and Date Types as base types.
In addition, the engine also knows `List`, `Map`, Sequences, Records and Beans.

The top level model is a `Map<String, Object>`, which contains the top level value by their names.

.Example Model
[source,java]
----
Map<String, Object> model = Map.of("father", father, "mother", mother);
----

The following tables show all model types supported by FreshMarker.
Because FreshMarker can be extended, there are more types available
footnote:[The library https://gitlab.com/schegge/telephone[Telephone] adds the `InternationalPhoneNumber` support.].

.Supported Model Types
|===
|Type | Java Type(s) | Primitive type

|String|`String`|yes
|Number|`Long`, `Integer`, `Short`, `Byte`|yes
|Number|`long`, `int`, `short`, `byte`|yes
|Number|`Double`, `Float`, `double`, `float`|yes
|Boolean|`Boolean`, `boolean`|yes
|DateTime|`Instant`, `ZonedDateTime`, `LocalDateTime`, `Date`|yes
|Date|`LocalDate`, `java.sql.Date`|yes
|Time|`LocalTime`, `java.sql.Time`|yes
|Duration|`Duration`|yes
|File|`File`|yes
|Path|`Path`|yes
|Period|`Period`|yes
|Sequence|Lists|no
|Range|-|no
|Slice|-|no
|Map|Maps|no
|Bean|Beans|no
|Record|Top-Level Records|no
|Enum|Enums|yes
|Null|-|yes
|===

All primitive types, except Null, have a default representation via their `toString` method.
This must be considered with the enums, because the `toString` method can be overridden.

=== Lazy Values

Normally the values are written directly into the model.
Sometimes the cost of creating optional values is quite high.
In that case it would be a waste to calculate the values if they are not used.
However, since FreshMarker needs the values in the model, a compromise is made.
Instead of calculating the values immediately and placing them in the map, the calculation is inserted into the model as a `TemplateObjectSupplier`.
Their actual values are lazy evaluated only when accessed during processing.

.Example lazy values
[source,java]
----
Map<String, Object> model = Map.of(
        "familyTree", TemplateObjectSupplier.of(() -> fetchTreeFromDataBase(name)),
        "name", "Kayser"
    );
template.process(model)
----

In the example above, the `familyTree` value is lazy evaluated, when the variable is accessed during template processing.

=== Forbidden Types

Although many Java types are supported directly or as a Java Bean, some classes cannot be used. For security reasons, all classes from the `java`, `javax`, `sun` and `com.sun` packages are ignored.

if you desperately need one of these classes, you can declare it as an exception.

.Example allowed system classes
[source,java]
----
configuration.getSecurity().addAllowedClass(java.util.UUID.class);
configuration.getSecurity().addAllowedPackages(java.lang.annotation.Annotation.class);
configuration.getSecurity().addAllowedPackages("java.io");
----

In the example above, the class `java.util.UUID` and all classes in the packages `java.lang.annotation` and `java.io` and all of their subpackages are allowed.