== Templates

A template engine generates output by creating a representation of a model using instructions in a template.

This complicated sentence can be better explained with a small example.

.Example Template
[source]
----
Hello ${example}!
----

The example template contains three parts.
A first literal text fragment ``Hello ``, an interpolation fragment `${name}` and a second literal text fragment `!`.
Literal text means the fragment is not interpreted in any particular way
footnote:[This is an example in the introduction, sometimes it's different, of course.].

=== Interpolations

The interpolation is a fragment, which is filled with data from the model.
The name `example` in the curly brackets is the name by which a value in the model can be identified.

.Example Model
[source,java]
----
Map<String, Object> model = Map.of("example", "World");
----

The example model contains a value `World` with the name `example`.

When the example template is processed, the template engine produces the output `Hello World!` based on the example model.

=== Directives

In addition, there is the possibility of hiding fragments in the template or repeating them several times.
There are special constructs for this, called directives.

.Example Template with directive
[source]
----
<#if example=='World'>
Hello ${example}!
<#else>
Hallo ${example}!
</#if>
----

Directives look like _HTML_ tags with a # before the tag name.
In this example, the English `Hello` is only written if the value is `World`.
In all other cases the German `Hallo` is written.

=== Built-Ins

Another important template concept is the built-in.
The result of an interpolation is changed by the built-ins.
The interpolation from the last example produces the output `World` from the value `World`.
If the interpolation is extended to `${example?uppercase}` then the interpolation produces `WORLD`.
In this case the built-in `upper_case` has been added.
Depending on the type of value, a wide variety of built-ins can be used.
footnote:[The library https://gitlab.com/schegge/holidays[Holidays] adds Built-Ins for Holidays].

=== Functions

Additional functionality can be added to the template-engine by custom Functions.

.Function Interface
[source,java]
----
public interface TemplateFunction {
  TemplateObject execute(ProcessContext context, List<TemplateObject> args);
}
----

A _Function_ is a Java class implementing the functional interface `TemplateFunction`.
It can be registered to the `Configuration` by the `registerFunction` method.

.Example Custom Function `abs` and `avg`
[source,java]
----
configuration = new Configuration();

configuration.registerFunction("abs", (context, args) ->
    args.get(0).evaluateToObject(context).asNumber().map(TemplateNumber::abs).orElseThrow());

configuration.registerFunction("avg", (context, args) ->
    args.stream().map(o -> o.evaluate(context, TemplateNumber.class)).reduce(TemplateNumber::add).orElseThrow().divide(new TemplateNumber(args.size())));
----

Each registered _Function_ can be called via a function call with its name as the function name.

.Example Usage of Custom Function
[source]
----
<#-- result 15 -->
${avg(10, 20)}

<#-- result 25 -->
${avg(10, 20, 30, 40)}

<#!-- result 10 -->
${abs(-10)}
----

=== Output Format and Escaping

Every Template is associated with an Output Format.
The Output Format defines the escaping rule for dynamically generated output.
Without escaping, there is a security risk known as template injection.
With template injection, dangerous fragments are injected into the output.

.Example Template Injection
[source]
----
<!-- title = "<script>alert("hallo")</script>"; -->
<h1>${title}</h1>
----

The example shows an _HTML_ fragment in which the text for a heading is to be inserted.
Without escaping, the script fragment is inserted and a more or less dangerous _Javascript_ is executed instead of displaying a title.

_FreshMarker_'s escape mechanism replaces the necessary meta characters of an output format to neutralize them.
The following table lists the supported output formats and their meta character replacements.
the last two lines indicate how comments can be inserted into the output using the @log directive.

.Output Formate
|===
| Name | Meta Characters | Replacements | Comment Prefix | Comment Suffix

| HTML
| `<`, `>`, `&`, `"`, `'`
| `\&lt;`, `\&gt;`, `\&amp;`,`\&quot;`, `&#39`;
| `<!--`
| ` -->`

| XHTML
| `<`, `>`, `&`, `"`, `'`
| `\&lt;`, `\&gt;`, `\&amp;`,`\&quot;`, `&#39`;
| `<!-- `
| ` -->`

| XML  | `<`, `>`, `&`, `"`, `'`
| `\&lt;`, `\&gt;`, `\&amp;`,`\&quot;`, `\&apos;`;
| `<!-- `
| ` -->`

| ADOC
2+| no escaping
| `////\n`
| `\n////\n`

| plainText
2+| no escaping
2+| no comments

| JavaScript
2+| no escaping
| `/* `
| ` */`

| CSS
2+| no escaping
| `/* `
| ` */`

| JSON
2+| no escaping
2+| no comments
|===

=== Template Loading

The `Configuration` class offers four methods for loading templates.

.Template Loading Methods
|===
| Method | Description

| `Template getTemplate(Path path);`
| Load template from path with default charset

| `Template getTemplate(Path path, Charset charset);`
| Load template from path with the given charset

| `Template getTemplate(String name, Reader reader);`
| Read template from the given reader

| `Template getTemplate(String name, String content);`
| Read template from the given string

| `Template getTemplate(Path importPath, String name, Reader reader);`
| Read template from the given reader

| `Template getTemplate(Path importPath, String name, String content);`
| Read template from the given string
|===

Regardless of the method selected for loading the template, the imports are loaded by the configured `TemplateLoader`.

By default, the `DefaultFileSystemTemplateLoader` is configured.
This loads all imports from the file system.

The `FileSystemTemplateLoader` can also be used with other file system implementations.

.`TemplateLoader` with the `ZipFileSystem`
[source,java]
----
FileSystem fs = FileSystems.newFileSystem(Paths.get("imports.zip"));
configuration.setTemplateLoader(new FileSystemTemplateLoader(fs));
----

In this example, the imports are loaded from the zip archive `imports.zip`.

Custom template loaders can also be used instead of the `DefaultFileSystemTemplateLoader`.
They have to implement the `TemplateLoader` interface.

[source,java]
----
public interface TemplateLoader {
    String getImport(Path path, String filename, Charset charset) throws IOException;

    default String getImport(Path path, String filename) throws IOException {
        return getImport(path, filename, Charset.defaultCharset());
    }
}
----

The `filename` parameter is the name of the import file and `path` is the parent directory of the template.
The parent directory can be used to load import files located relative to the template.

NOTE: For templates loaded by String or Reader the path is the current directory.

=== Template Caching

_FreshMarker_ does not know any caching mechanism, but you can store and reuse templates with any technology (_Maps_, _Singletons_, _Caches_) you like.

=== Partial Reduction

NOTE: This feature is in an experimental stage and should be used with care.

When processing a template, all necessary data must be available in the model.
Otherwise, an exception is thrown if data is missing during processing.
If the template contains values that remain the same for a large number of evaluations,
the template can be preprocessed.

.Example Template with reduction on company
[source,java]
----
Template template = configuration.getTemplate("test", """"
   <#list employee as e>${e.firstname}.${e.lastname}@${company.domain}</#list>
   """);
Template reducedTemplate = template.reduce("company", new Company("schegge.de"));
----

The reduce method receives some of the necessary data and partially evaluates the template.
As a result, it delivers a new template in which part of the structure has been simplified.

WARNING: A reduction cannot be carried out if loop variables, the default or exist operator are used. Variables and parameter should not hide model variables, this could be produced unprodicted results.