=== Period Built-Ins

The Built-Ins in the examples operate on the value `P1Y2M3D`.

==== `c` (computer language) Built-In (since 1.6.1)

This built-in returns a period string of the value.

|===
| Interpolation | Output | Type

m|${temporal?c}
m|P1Y2M3D
|string
|===

==== `h` (human language) Built-In (since 1.6.1)

This built-in returns a localized period string of the value. The year, month and day values are comma separated.

include::localization_tip.adoc[]

|===
| Interpolation | Output | Type

m|${temporal?h}
m|1 year, 2 months, 3 days
|string
|===

==== `years` Built-In (since 1.6.1)

This built-in returns the years of the value as a number.

|===
| Interpolation | Output | Type

m|${temporal?years}
m|1
|number
|===

==== `months` Built-In (since 1.6.1)

This built-in returns the months of the value as a number.

|===
| Interpolation | Output | Type

m|${temporal?months}
m|2
|number
|===

==== `days` Built-In (since 1.6.1)

This built-in returns the days of the value as a number

|===
| Interpolation | Output | Type

m|${temporal?days}
m|3
|number
|===
