== Directives

=== If/ElseIf/Else Directive

This directive generates conditional output. The expression in the `if` and `elseif` statement
is evaluated to a boolean value. If the value is `true` the corresponding block is evaluated.
If the expression cannot evaluate to a boolean value an exception is thrown.

.Example with only the `if` part
[source,freshmarker]
----
<#if text??>
${text}
</#if>
----

The `elseif` and `else` part are optional and can be dismissed.

.Example with all parts
[source,freshmarker]
----
<#if number >= 100>
greater equal hundred
<#elseif number > 10>
greater ten
<#else>
less ten
</#if>
----

=== Switch/Case/Default Directive

This directive generates conditional output.
But unlike the _If Directive_, only one expression in the `switch` statement is evaluated.
Each `case` statement handles a possible outcome of the evaluation.
If none of the specified `case` statements match, then the optional `default` statement is used.

NOTE: The _FreshMarker_ _Switch Directive_ does not support fall-through, so `break` statements are unnecessary and therefor not supported.

[source,freshmarker]
----
<#switch color>
<#case 'RED'>#FF0000
<#case 'GREEN'>#00FF00
<#case 'BLUE'>#0000FF
<#default>${color}
</#switch>
----

include::directives-list.adoc[]

=== Var/Set Directive

The _Var_ and _Set Directives_ are used to define local variables in the template. 
Unlike the model values, new values can be assigned to variables. 

The first use of a variable is with the _Var Directive_. This defines the variables in the current context. 
Later, the variable can be assigned new values with the _Set Directive_. A variable only exists within its context. 

[source,freshmarker]
----
<#var test='eins'/>
<#set test='zwei'/>
<#set test='drei'/>
----

A new context is created within the _List Directive_, _Macro Directive_ and the conditional _If_ and _Switch Directives_.
Therefore, variables that are created in a _Macro Directive_ can no longer be accessed outside.

.Example variable context
[source,freshmarker]
----
<#macro copyright>
  <#var test='test'/>
</#macro>
<@copyright/>
${test!'gonzo'}
----

In this example the variable `test` cannot accessed outside of the macro.
The result of the interpolation `${test!'gonzo'}` is therefore `gonzo`.

Variables with an identical name cannot created in the same context.
Variables in an outer context can be hidden by variables with an identical name.

=== Output-Format Directive

The output-format directive changes the current output format of the template.
The new output format remains in place until it is changed by another output-format directive.

[source,freshmarker]
----
<#outputformat 'HTML'>
${text}
<#outputformat 'plainText'>
${text}
----

=== Setting Directive

The _Setting Directive_ changes some standard values in the template.
The settings remains in place until is is changed by another settings directive.

[source,freshmarker]
----
<#setting locale="de-DE">
${42.23}
<#setting locale="en-US">
${42.23}
----

=== Macro Directive

The macro directive can be used to create a macro, which can then be used as a user directive in the template.

[source,freshmarker]
----
<#macro copyright from>
/*
 * Copyright © ${from}-${.now?string('yyyy')} Jens Kaiser
 *
 * All Rights resevered.
 */
</#macro from>
<@copyright/>
----

=== User Directive

[source,freshmarker]
----
<@log level='info' message='test'/>
----

=== Import Directive (since 1.0.0)

Macros can be loaded by the `import` directive.

[source,freshmarker]
----
<#import 'macros.fmt' as m/>
----

The file name parameter is the name of the import file and will be loaded by default relative to the template file.

[source,freshmarker]
----
<#import 'macros.fmt' as m/>
<@m.copyright/>
----

=== Brick Directive (since 1.6.6)

It is clearer if related templates are contained in the same document. The document can be evaluated as a template as a whole or the templates it contains can be evaluated individually.

A part that can be evaluated individually is contained within a brickfootnote:[Usually, this is called a template fragment, but the technical _FreshMarker_ template component classes are already called fragments.] directive.

.Example mail template
[source,freshmarker]
----
<#brick 'salutation'>Hello ${customer.first} ${customer.last},</#brick>
<#brick 'signature'>
Best regards
${employee.first} ${employee.last}
${employee.title}
</#brick>
----

A single brick directive is evaluated with the `Template#processBrick(String, Map)` method. The `String` parameter is the name of the directive.

.Example brick rendering
[source,java]
----
Map<String, Object> model = Map.of("customer", customer, "employee", employee);
Configuration configuration = new Configuration();
Template template = configuration.getTemplate("mail", mail);
String salutation = template.processBrick("salutation", model);
String signature = template.processBrick("signature", model);
----
