== Directives

=== If/ElseIf/Else Directive

This directive generates conditional output. The expression in the `if` and `elseif` statement
is evaluated to a boolean value. If the value is `true` the corresponding block is evaluated.
If the expression cannot evaluate to a boolean value an exception is thrown.

.Example with only the `if` part
[source]
----
<#if text??>
${text}
</#if>
----

The `elseif` and `else` part are optional and can be dismissed.

.Example with all parts
[source]
----
<#if number >= 100>
greater equal hundred
<#elseif number > 10>
greater ten
<#else>
less ten
</#if>
----

=== Switch/Case/Default Directive

This directive generates conditional output.
But unlike the _If Directive_, only one expression int the `switch` statement is evaluated.
Each `case` statement handles a possible outcome of the evaluation.
If none of the specified `case` statements match, then the `default` statement is used.

NOTE: The _FreshMarker_ _Switch Directive_ does not support fall-through, so `break` statements are unnecessary.

[source]
----
<#switch color>
<#case 'RED'>#FF0000
<#case 'GREEN'>#00FF00
<#case 'BLUE'>#0000FF
<#default>${color}
</#switch>
----

include::directives-list.adoc[]

=== Var/Set Directive

[source]
----
<#var test='eins'/>
<#set test='zwei'/>
<#set test='drei'/>
----

=== Output-Format Directive

TBD

=== Setting Directive

[source]
----
<#setting locale="de_DE">
${42.23}
<#setting locale="en_US">
${42.23}
----

=== Macro Directive

TBD

=== User Directive

[source]
----
<@log level='info' message='test'/>
----

