=== List Directive

The _List Directives_ processes its body for each element of a sequence. The sequence can be either a list, a hash or a range. A _List Directive_ defines the sequence and the name of the item variable in the block. In addition, an optional loop variable containing meta information of the current loop iteration can also be specified.

IMPORTANT: Although _FreeMarker_ and _FreshMaker_ are similar, the list directive syntax differs. _FreeMarker_ does not know a separate loop variable. In addition, _FreshMaker_ does not support an _Else_ element in the list. This can be replaced by a separate _If Directive_. _FreeMarker_'s _Items Directive_ is also not supported. there are plenty of ways to get the same result.

==== List Directive with a list

A list is a sequence of values of any model type.

.List Directive example with a list
[source]
----
<#list sequence as s>
${s} Marx
</#list>
----

In the above example, each element from the list is simply output followed by the word `Marx`.
If the list contains `Chico`, `Harpo`, `Groucho`, `Gummo` and `Zeppo` then the result is a five-line listing of the Marx brothers.

The next example the interpolation `${s}` is preceded by the interpolation `${l?counter}`.

.List Directive example with a list and a loop variable
[source]
----
<#list sequence as s with l>
${l?counter}. ${s} Marx
</#list>
----

Because `l` is the name of the loop variable, the first interpolation evaluates to the counter of the current item in the list.

[source]
----
1. Chico Marx
2. Harpo Marx
3. Groucho Marx
4. Gummo Marx
5. Zeppo Marx
----

==== List Directive with a range

A range is defined by a lower and a non-mandatory upper numerical limit.
Although _FreshMarker_ also masters right-open ranges, _List Directives_ are not allowed to use them.

.List Directive example with a range
[source]
----
<#list 1..5 as s>
${s} * ${s} = ${s*s}
</#list>
----

The current item in the above example is any integer value from 1 to 5 inclusive.
The result is a list of square value equations.

[source]
----
1 * 1 = 1
2 * 2 = 4
3 * 3 = 9
4 * 4 = 16
5 * 5 = 25
----

Because the limits of a range do not have to be constants, a List Directive can also be used to mimic a for loop.

.List Directive example with variable range limits
[source]
----
<#list a..b as s>
${s} * ${s} = ${s*s}
</#list>
----

This example loops through all values between numeric variable `a` and numeric variable `b`.
For the value `3` in `a` and `1` in `b` the following result is generated.

[source]
----
3 * 3 = 9
2 * 2 = 4
1 * 1 = 1
----

==== List Directive with a hash

A hash is a sequence of key-value pairs. The key is a string and the value is any model type.
For a hash the item in the List Directive is a key-value pair.

.List Directive example with a hash
[source]
----
<#list map as key, value>
${key}->${value}
</#list>
----

NOTE: In addition to the _Java_ `Map` types, _Java Beans_ are also interpreted as a hash. It is not only possible to iterate over the enries of a `Map`, but also over the attributes of a Bean.

.List Directive example with a hash and a loop variable
[source]
----
<#list map as key, value with l>
${l?counter}. ${key}->${value}
</#list>
----
