== Directives

=== If/ElseIf/Else Directive

This directive generates conditional output. The expression in the `if` and `elseif` statement
is evaluated to a boolean value. If the value is `true` the corresponding block is evaluated.
If the expression cannot evaluate to a boolean value an exception is thrown.

.Example with only the `if` part
[source]
----
<#if text??>
${text}
</#if>
----

The `elseif` and `else` part are optional and can be dismissed.

.Example with all parts
[source]
----
<#if number >= 100>
greater equal hundred
<#elseif number > 10>
greater ten
<#else>
less ten
</#if>
----

=== Switch/Case/Default Directive

This directive generates conditional output.
But unlike the _If Directive_, only one expression in the `switch` statement is evaluated.
Each `case` statement handles a possible outcome of the evaluation.
If none of the specified `case` statements match, then the optional `default` statement is used.

NOTE: The _FreshMarker_ _Switch Directive_ does not support fall-through, so `break` statements are unnecessary and therefor not supported.

[source]
----
<#switch color>
<#case 'RED'>#FF0000
<#case 'GREEN'>#00FF00
<#case 'BLUE'>#0000FF
<#default>${color}
</#switch>
----

include::directives-list.adoc[]

=== Var/Set Directive

The _Var_ and _Set Directives_ are used to define local variables in the template. 
Unlike the model values, new values can be assigned to variables. 

The first use of a variable is with the _Var Directive_. This defines the variables in the current context. 
Later, the variable can be assigned new values with the _Set Directive_. A variable only exists within its context. 
A new context is created within the _List Directive_ and the conditional _If_ and _Switch Directives_. 
Therefore, variables that are created in a _List Directive_ can no longer be accessed outside.

[source]
----
<#var test='eins'/>
<#set test='zwei'/>
<#set test='drei'/>
----

Variables with an identical name cannot created in the same context. 
Variables in an outer context can be hidden by variable s with an identical name.

=== Output-Format Directive

TBD

=== Setting Directive

The _Setting Directive_ changes some standard values in the template.

[source]
----
<#setting locale="de_DE">
${42.23}
<#setting locale="en_US">
${42.23}
----

=== Macro Directive

[source]
----
<#macro copyright from>
/*
 * Copyright © ${from}-${.now?string('yyyy')} Jens Kaiser
 *
 * All Rights resevered.
 */
</#macro>
<@copyright/>
----

=== User Directive

[source]
----
<@log level='info' message='test'/>
----

=== Import Directive (since 1.0.0)

Macros can be loaded by the `import` directive.

[source]
----
<#import 'macros.fmt' as m/>
----

The file name parameter is the name of the import file and will be loaded by default relative to the template file.

[source]
----
<#import 'macros.fmt' as m/>
<@m.copyright/>
----
