== Extension API (since 1.8.0)

=== Overview

The `Extension` mechanism replaces the previous `PlugInProvider` mechanism. Although the previous plug-in mechanism worked well, it shows weaknesses when extending FreshMarker.

=== Registering Extensions

`Extensions` can be registered _automatically_ via the Java `ServiceLoader` mechanism or _programmatically_.

==== Automatic Extension Registration

`Extensions` can be registered _automatically_ via the
Java `ServiceLoader` mechanism. This allows third-party `Extensions` to be automatically recognized and registered, depending on what is available in the classpath.

Specifically, a custom `Extension` can be registered by specifying its fully qualified class name in a file named `org.freshmarker.api.extension.Extension` in the `/META-INF/services` folder in the associated JAR file.

==== Programmatic Extension Registration

Developers can register `Extension` programmatically by calling the `Configuration#register(Extension)` method.

When an `Extension` is registered automatically, it can only be configured via template features. In contrast, when an `Extension` is registered programmatically, it can be modified via constructor arguments or setter methods.

==== Extension Order

The `Extension` are registered in a deterministic order. The default `Extension` are registered first, followed by the _automatic_ `Extension` and then the _programmatic_ `Extension`.

include::features.adoc[]

include::built-ins.adoc[]

=== Additional Built-In Variables

The `BuiltInVariableProvider` defines the API for `Extensions` that wish to add new built-in variables.

Each custom built-in variable has to implement the `BuiltInVariable` interface.

.Example BuiltInVariable
[source,java,,role="primary"]
----
public class ExampleBuiltInVariable implements BuiltInVariable {
    public TemplateObject apply(ProcessContext context) {
        new TemplateString("EXAMPLE");
    }
}
----

.Example BuiltInVariable as Lambda
[source,java,role="secondary"]
----
(context) -> new TemplateString("EXAMPLE");
----

Since each `BuiltInVariable` has a name, the `BuiltInVariableProvider` returns the built-in variables as `Map<String,BuiltInVariable>`.

.Example BuiltInVariableProvider
[source,java]
----
public final class ExampleBuiltInProvider implements BuilInProvider {
    public Map<String,BuiltInVariable> provideBuiltIns() {
        Map.of("example", (context) -> new TemplateString("EXAMPLE"));
    }
}
----

=== Additional User Directives

The `UserDirectiveProvider` defines the API for `Extensions` that wish to add new user directives.

Each custom user directive hast to implement the `UserDirective` interface.

.Example UserDirective
[source,java,role="primary"]
----
public class ExampleUserDirective implements UserDirective {
    public execute(ProcessContext context, Map<String, TemplateObject> args, Fragment body) {
        body.process(context);
        body.process(context);
    }
}
----

.Example UserDirective as Lambda
[source,java,role="secondary"]
----
(context, args, body) -> { body.process(context); body.process(context); };
----

Since each `UserDirective` has a name, the `UserDirectiveProvider` returns the user directives as `Map<String,UserDirective>`.

.Example UserDirectiveProvider
[source,java]
----
public final class ExampleUserDirectiveProvider implements UserDirectiveProvider {
    public Map<String,UserDirective> provideUserDirectives() {
        Map.of("example", new ExampleUserDirective());
    }
}
----

TBD

=== Additional Function

The `FunctionProvider` defines the API for `Extensions` that wish to add new template functions.

Each custom template function hast to implement the `TemplateFunction` interface.

.Example TemplateFunction
[source,java,role="primary"]
----
public class ExampleFunction implements TemplateFunction {
    public TemplateObject execute(ProcessContext context, List<TemplateObject> args) {
        return TemplateNumber.of(args.size());
    }
}
----

.Example UserDirective as Lambda
[source,java,role="secondary"]
----
(context, args) -> TemplateNumber.of(args.size());
----

Since each `TemplateFunction` has a name, the `FunctionProvider` returns the user directives as `Map<String,TemplateFunction>`.

.Example FunctionProvider
[source,java]
----
public final class ExampleFunctionProvider implements UserDirectiveProvider {
    public Map<String,TemplateFunction> provideFunctions() {
        Map.of("example", (context, args) -> TemplateNumber.of(args.size()));
    }
}
----


=== Additional Formatter

The `FormatterProvider` defines the API for `Extensions` that wish to add new formatter.

TBD

=== Additional Type Mapper

The `TypeMapperProvider` defines the API for `Extensions` that wish to add new type mapper.

TBD

=== Additional Template-Object Provider

The `TemplateObjectProviders` defines the API for `Extensions` that wish to add new template-object providers.

TBD

=== Additional Output Formats

The `OutputFormatProviders` defines the API for `Extensions` that wish to add new output formats.

TBD
