== Extension API (since 1.8.0)

=== Overview

The `Extension` mechanism replaces the previous `PlugInProvider` mechanism. Although the previous plug-in mechanism worked well, it shows weaknesses when extending FreshMarker.

=== Registering Extensions

`Extensions` can be registered _automatically_ via the Java `ServiceLoader` mechanism or _programmatically_.

==== Automatic Extension Registration

`Extensions` can be registered _automatically_ via the
Java `ServiceLoader` mechanism. This allows third-party `Extensions` to be automatically recognized and registered, depending on what is available in the classpath.

Specifically, a custom `Extension` can be registered by specifying its fully qualified class name in a file named `org.freshmarker.api.extension.Extension` in the `/META-INF/services` folder in the associated JAR file.

==== Programmatic Extension Registration

Developers can register `Extension` programmatically by calling the `Configuration#register(Extension)` method.

When an `Extension` is registered automatically, it can only be configured via template features. In contrast, when an `Extension` is registered programmatically, it can be modified via constructor arguments or setter methods.

==== Extension Order

The `Extension` are registered in a deterministic order. The default `Extension` are registered first, followed by the _automatic_ `Extension` and then the _programmatic_ `Extension`.

include::features.adoc[]

include::built-ins.adoc[]

include::built-in-variables.adoc[]

include::user-directives.adoc[]

include::functions.adoc[]

=== Additional Formatter

The `FormatterProvider` defines the API for `Extensions` that wish to add new formatter.

TBD

=== Additional Type Mapper

The `TypeMapperProvider` defines the API for `Extensions` that wish to add new type mapper.

TBD

=== Additional Template-Object Provider

The `TemplateObjectProviders` defines the API for `Extensions` that wish to add new template-object providers.

TBD

=== Additional Output Formats

The `OutputFormatProviders` defines the API for `Extensions` that wish to add new output formats.

TBD
