== Built-Ins

Built-Ins are interpolation operations which are called on the current value of the interpolation.

.Example with `upper_case` built-in
[source,java]
----
private final Configuration configuration = new Configuration();
private Template template = configuration.getTemplate("test", "HELLO ${example?upper_case}!");
System.out.println(template.process(Map.of("example", "world")));
----

In the above example the built-in `upper_case` is called on the current value `world` of the interpolation.
The built-in converts a text to its uppercase form.

Since the capitalization can only be changed for text, the execution of this built-in on other types such as numbers or dates is forbidden. In general, all built-ins are assigned to a type and an exception is thrown if a wrong type is used.

if a built-in seems to apply to multiple types, it's because each type has a built-in with the same name.

It is possible to use more than one built-in in an interpolation.
The built-ins are called from left to right on the current value of the interpolation.
This means a built-in is called on the result of a previous built-in or the initial value.

.Example with two built-ins
[source,java]
----
private final Configuration configuration = new Configuration();
private Template template = configuration.getTemplate("test", "HELLO ${example?upper_case?lowercase}!");
System.out.println(template.process(Map.of("example", "WorlD")));
----

In the example above the `upper_case` built-in is called on the current value `WorlD`.
The second built-in `lower_case` is called on the current value `WORLD`, which is the result of `upper_case`.
the result of the interpolation is the result `world` of the second built-in.

[NOTE]
====
Since _FreshMarker 1.3.2_ the File and Paths BuiltIns are included via an additional artefact.

[source,xml]
----
<dependency>
  <groupId>de.schegge</groupId>
  <artifactId>freshmarker-file</artifactId>
  <version>1.0.0</version>
</dependency>
----
====

include::builtins-string.adoc[]

include::builtins-boolean.adoc[]

include::builtins-number.adoc[]

include::builtins-datetime.adoc[]

include::builtins-date.adoc[]

include::builtins-time.adoc[]

include::builtins-looper.adoc[]

include::builtins-enum.adoc[]

include::builtins-filepath.adoc[]

include::builtins-locale.adoc[]

include::builtins-version.adoc[]
