=== Number Built-Ins

==== `c` (computer language) Built-In

This built-in converts a boolean to the string using the `toString()` method of the corresponding base types `Double`, `Float`, `Long`, `Integer`, `Byte` or `Short`.

NOTE: Without this builtin, the number is formatter with the default number formatted for the current locale.

==== `format` Built-In

This built-in format the number by the given format parameter and the current locale. See `java.util.Formatter` for details.

|===
|Interpolation | Locale | Output

m|${3.14159?format("%.2f")}
m|Locale.GERMANY
m|3.14

m|${3.14159?format("%.4f")}
m|Locale.US
m|3.1416
|===

==== `abs` Built-In

This built-in return the absolute value of the number.

|===
|Interpolation | Output

m|${-3.14159?abs}
m|3.142

m|${3.14159?abs}
m|3.142

m|${-42?abs}
m|42
|===

==== `sign` Built-In

This built-in return the sign of the number as an Integer.

|===
|Interpolation | Output

m|${-3.14159?sign}
m|-1

m|${3.14159?sign}
m|1

m|${0?sign}
m|0
|===

==== Cast Built-Ins (since 1.0.0)

These built-ins cast the number to a TemplateNumber instance in the specified type range.

|===
|Interpolation | Output | Type

m|${42?byte}
m|42
m|byte

m|${42?short}
m|42
m|short

m|${42?int}
m|42
m|integer

m|${42?long}
m|42
m|long

m|${42.0?float}
m|42.0
m|float

m|${42.0?double}
m|42.0
m|double
|===
