=== Date Built-Ins

The Built-Ins in the examples operate on the `java.time.LocalDate` respectively `java.sql.Date` value `1968-08-24`.

==== `date` Built-In

This built-in returns the date part of the value.

|===
| Interpolation | Output | Type

m|${temporal?c}
m|1968-08-24
|date
|===

==== `c` (computer language) Built-In

This built-in returns a date string of the value.

|===
| Interpolation | Output | Type

m|${temporal?c}
m|1968-08-24
|string
|===

==== `h` (human language) Built-In (since 1.4.6)

This built-in returns a date string of the value.
If the date is a maximum of two days before or after the reference date, a localized variant of the
`the day before yesterday`, `yesterday`, `today`, `tomorrow` or `the day after tomorrow` is used.
The reference date is the parameter of the built-in.
If the parameter is missing, `LocalDate.now()` is used.

It is only available for the `TemplateLocalDate` type.

[TIP]
====
Localizations is only supported for `de`, `en` and `fr`.
If you need another one or want to change a supported one put a resource file `freshmarker_xx.properties` on the classpath.
It should contain all localized values of the original ones where `xx` is the selected language.

.default values in `freshmarker.properties`
----
include::../../resources/freshmarker.properties[]
----
====

|===
| Interpolation | Output | Type

m|${temporal?h}
m|today
|string

m|${temporal?h(.now)}
m|1968-08-24
|date

m|${dayBeforeTemporal?h(temporal)}
m|yesterday
|string

|===

==== `string` Built-In

This built-in returns a formatted string of the value.
footnote:legacyTemporal[]

|===
| Interpolation | Output | Type

m|${temporal?string('dd. MMMM yyyy')}
m|24. August 1968
|string
|===
