=== Date Built-Ins

The Built-Ins in the examples operate on the `java.time.LocalDate` respectively `java.sql.Date` value `1968-08-24`.

==== `date` Built-In

This built-in returns the date part of the value.

NOTE: This built-in seems pointless at first because the result corresponds to the original value. However, it is often not certain what type the variable actually has. With a `datetime` value, the time would otherwise also be used without `?date`.

|===
| Interpolation | Output | Type

m|${temporal?c}
m|1968-08-24
|date
|===

==== `c` (computer language) Built-In

This built-in returns a date string of the value.

|===
| Interpolation | Output | Type

m|${temporal?c}
m|1968-08-24
|string
|===

==== `h` (human language) Built-In (since 1.4.6)

This built-in returns a date string of the value.
If the date is a maximum of two days before or after the reference date, a localized variant of the
`the day before yesterday`, `yesterday`, `today`, `tomorrow` or `the day after tomorrow` is used.
The reference date is the parameter of the built-in.
If the parameter is missing, `LocalDate.now()` is used.
footnote:legacyTemporal[]

include::localization_tip.adoc[]

|===
| Interpolation | Output | Type

m|${.now?h}
m|today
|string

m|${temporal?h(.now)}
m|1968-08-24
|date

m|${dayBeforeTemporal?h(temporal)}
m|yesterday
|string

|===

==== `string` Built-In

This built-in returns a formatted string of the value.
footnote:legacyTemporal[]

|===
| Interpolation | Output | Type

m|${temporal?string('dd. MMMM yyyy')}
m|24. August 1968
|string
|===

==== `since` Built-In (since 1.6.1)

This built-in returns a duration between the value and the parameter.
If the parameter is missing, `java.time.LocalDate.now()` is used.
footnote:legacyTemporal[]

|===
| Interpolation | Output | Type

m|${tomorrow?since}
m|P1D
|duration

m|${tomorrow?since(yesterday)}
m|P2D
|duration
|===

==== `until` Built-In (since 1.6.1)

This built-in returns a duration between the value and the parameter.
If the parameter is missing, `java.time.LocalDate.now()` is used.
footnote:legacyTemporal[]

|===
| Interpolation | Output | Type

m|${yesterday?until}
m|P1D
|duration

m|${yesterday?until(tomorrow)}
m|P2D
|duration
|===
